### PR TITLE
Fix broken image links

### LINKED ISSUE #5: Readme has broken image links
This repo's [readme.md](https://github.com/layer5io/gowrk2/blob/master/README.md) is missing a couple images that need to be copied over to this repo.

### PR DESCRIPTION
**Pull request by Adeola-Adesoba**
This fixes #5

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Hi @Adeola-Adesoba, thanks for this.

You'll want to ensure that the URL you're using to refer to the images uses either a relative URL (e.g., `./github/img/readme/slack.png`) or an absolute URL that refers to the image directly (e.g. `https://raw.githubusercontent.com...`).

**Comment by Adeola-Adesoba** [comment]
@leecalcote thanks for your comment. I tried doing that already. I am presently using an absolute path. Maybe someone else can take a look as nothing I am doing seems to be right.

**Review by leecalcote — APPROVED** [review]
@Adeola-Adesoba I made a slight tweak. Thanks for this PR. I think we're good to go. 👍

**Comment by leecalcote** [comment]
> @leecalcote thanks for your comment. I tried doing that already. I am presently using an absolute path. Maybe someone else can take a look as nothing I am doing seems to be right.

You bet. Here's an example of an absolute URL that will directly reference an image on GitHub - https://raw.githubusercontent.com/layer5io/gowrk2/master/.github/readme/images/slack-128.png

**Comment by Adeola-Adesoba** [comment]
> > @leecalcote thanks for your comment. I tried doing that already. I am presently using an absolute path. Maybe someone else can take a look as nothing I am doing seems to be right.
> 
> You bet. Here's an example of an absolute URL that will directly reference an image on GitHub - https://raw.githubusercontent.com/layer5io/gowrk2/master/.github/readme/images/slack-128.png

Thank you @Lee

**Comment by leecalcote** [comment]
Absolutely. 👍

**Pull request merged**
