### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Adeola-Adesoba**
Signed-off-by: Adeola Adesoba <adeoladee92@gmail.com>

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Thank you, @Adeola-Adesoba. It looks like you signed your commit. But, the check failed for some reason. Will you execute the steps? https://github.com/layer5io/gowrk2/pull/4/checks?check_run_id=880625049

**Review by leecalcote — APPROVED** [review]
Thank you 👍

**Comment by Adeola-Adesoba** [comment]
> Thank you 👍

You are welcome. The PR is not closed yet 😄

**Comment by leecalcote** [comment]
Hi @Adeola-Adesoba, will you take a look at issue #5?

**Pull request merged**
